"""Add date column to activity table

Revision ID: 232bbab78c10
Revises: 1a856173147e
Create Date: 2024-05-31 20:33:10.659434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '232bbab78c10'
down_revision = '1a856173147e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('calories', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('type', sa.String(length=100), nullable=False))
        batch_op.alter_column('steps',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('distance',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_column('activity_type')
        batch_op.drop_column('calories_burned')
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('calories_burned', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('activity_type', sa.VARCHAR(length=50), nullable=False))
        batch_op.alter_column('distance',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('steps',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('type')
        batch_op.drop_column('calories')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
